### ISSUE TITLE
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (When reloading scripts)

### ISSUE THREAD

**Issue by rlguy** [jlampel/extra_lights#20]
### Version Info

**Blender version:** 2.83
**Extra Lights version:** 1.0

### Description

I often use the Blender **F3 > Reload Scripts** operator during addon development and noticed this error from the Extra Lights addon:

```
Read prefs: C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: C:\Users\ryanl\Downloads\blender-2.83.0-windows64\2.83\python
Exception in module unregister(): 'C:\\Users\\ryanl\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons\\extra_lights\\__init__.py'
Traceback (most recent call last):
  File "C:\Users\ryanl\Downloads\blender-2.83.0-windows64\2.83\scripts\modules\addon_utils.py", line 434, in disable
    mod.unregister()
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\extra_lights\__init__.py", line 32, in unregister
    ui.unregister()
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\extra_lights\ui.py", line 109, in unregister
    unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
Reloading: <module 'bl_operators' from 'C:\\Users\\ryanl\\Downloads\\blender-2.83.0-windows64\\2.83\\scripts\\startup\\bl_operators\\__init__.py'>
Reloading: <module 'bl_ui' from 'C:\\Users\\ryanl\\Downloads\\blender-2.83.0-windows64\\2.83\\scripts\\startup\\bl_ui\\__init__.py'>
Reloading: <module 'keyingsets_builtins' from 'C:\\Users\\ryanl\\Downloads\\blender-2.83.0-windows64\\2.83\\scripts\\startup\\keyingsets_builtins.py'>
Reloading: <module 'nodeitems_builtins' from 'C:\\Users\\ryanl\\Downloads\\blender-2.83.0-windows64\\2.83\\scripts\\startup\\nodeitems_builtins.py'>
Exception in module register(): C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\extra_lights\__init__.py
Traceback (most recent call last):
  File "C:\Users\ryanl\Downloads\blender-2.83.0-windows64\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\extra_lights\__init__.py", line 29, in register
    ui.register()
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\extra_lights\ui.py", line 101, in register
    register_class(cls)
ValueError: register_class(...): already registered as a subclass 'OBJECT_OT_add_light'
```

This causes classes of the addon not to be completely registered:

![missing_lights](https://user-images.githubusercontent.com/4285191/85060649-70735100-b15a-11ea-87dc-6656f47241bc.jpg)

A simple workaround is to restart Blender so that the addon can register all classes.

### To reproduce:
1. Open Blender
2. Run operator: F3 > Reload Scripts
3. View Blender System Console for error

---

Loving the addon, by the way!

**Comment by jlampel** [comment]
Hey Ryan, thank you for reporting this! I believe I've fixed this in the update I'm currently working on, but I will double check again before releasing it to make sure.

**Comment by jlampel** [comment]
Sorry this took awhile, but it should be fixed. If you run into any issues with it not registering all the way again please let me know. Thanks!
